version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      NODE_ENV: development
      DATABASE_HOSTNAME: db
      DATABASE_PORT: '3306'
      DATABASE_PASSWORD: root
      DATABASE_USER: root
      DATABASE_NAME: job_hunt_diary
    ports:
      - '4000:4000'
      - '9229:9229'
    depends_on:
      - db
      - phpmyadmin
    networks:
      - job_hunt_diary
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_hunt_diary
    ports:
      - "3308:3306"
    networks:
      - job_hunt_diary
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - job_hunt_diary
volumes:
  dbdata:
networks:
  job_hunt_diary: {}