version: '3.8'
services:
  api-test:
    build:
      context: ./api
      dockerfile: Dockerfile.test
      args:
        db_host: db-test
        db_port: 3306
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      NODE_ENV: test
      DATABASE_HOSTNAME: db-test
      DATABASE_PORT: '3306'
      DATABASE_PASSWORD: root
      DATABASE_USER: root
      DATABASE_NAME: job_hunt_diary-test
    ports:
      - '9228:9229'
    depends_on:
      - db-test
    networks:
    - unit-test-network
  db-test:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_hunt_diary-test
    networks:
      - unit-test-network
  phpmyadmin-test:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db-test
    environment:
      PMA_HOST: db-test
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "4001:80"
    networks:
      - unit-test-network
networks:
  unit-test-network: {}
