version: '3.7'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/api
      - ./api/node_modules
    environment:
      NODE_ENV: development
    ports:
      - '4000:4000'
