apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
  - protocol: 'TCP'
    port: 4000
    targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: graphql-api
          image: whoisju1/job-hunt-diary-api:latest
          ports:
          - containerPort: 4000
          env:
            - name: NODE_ENV
              value: 'Production'


