env:
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  sort-keys:
    - error
    - asc
    - caseSensitive: true
      natural: true
      miniKeys: true
  sort-imports:
    - error
    - asc
  spaced-comment:
    - error
  block-spacing:
    - error
    - always
  eol-last:
    - error
    - always
  no-trailing-spaces:
    - error
  no-var:
    - error