env:
  commonjs: true
  es2021: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  # - plugin:@typescript-eslint/eslint-recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  project: ['./tsconfig.json']
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-catch-shadow:
    - error
  no-shadow:
    - error
    - builtinGlobals: false
      hoist: functions
  no-undef-init:
    - error
  eol-last:
    - error
    - always
  max-depth:
    - warn
  max-lines-per-function:
    - warn
  max-params:
    - warn
  sort-imports:
    - error
  sort-keys:
    - error
  sort-vars:
    - error
    - ignoreCase: false
  no-var:
    - error

  # following rules disabled so as not report incorrect errors because of typscript rules
  comma-dangle: "off"
  default-param-last: "off"
  no-duplicate-imports: "off"
  no-extra-parens: "off"
  prefer-readonly: "off"
  no-empty-interface: "off"
  no-floating-promises: "off"
  no-use-before-define: "off"
  no-unused-vars: "off"
  no-redeclare: "off"
# ---- typescript rules ---
  '@typescript-eslint/prefer-readonly':
    - error
    - onlyInlineLambdas: true
  '@typescript-eslint/no-empty-interface':
    - error
    - allowSingleExtends: true
  '@typescript-eslint/no-floating-promises':
    - error
  '@typescript-eslint/no-inferrable-types':
    - error
  '@typescript-eslint/no-unnecessary-condition':
    - error
  '@typescript-eslint/no-unnecessary-type-assertion':
    - error
  '@typescript-eslint/comma-dangle':
    - error
    - "always-multiline"
  '@typescript-eslint/default-param-last':
    - error
  '@typescript-eslint/no-duplicate-imports':
    - error
  '@typescript-eslint/no-extra-parens':
    - error
  '@typescript-eslint/no-extra-semi':
    - error
  '@typescript-eslint/no-unused-vars':
    - error
  '@typescript-eslint/no-redeclare':
    - error
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
      classes: false
  '@typescript-eslint/no-misused-promises':
    - error
    - ignoreIIFE: true
      ignoreVoid: true