env:
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-catch-shadow:
    - error
  no-shadow:
    - error
    - builtinGlobals: false
      hoist: functions
  no-undef-init:
    - error
  no-unused-vars:
    - error
  eol-last:
    - error
    - always
  max-depth:
    - warn
  max-lines-per-function:
    - warn
  max-params:
    - warn
  sort-imports:
    - error
  sort-keys:
    - error
  sort-vars:
    - error
    - ignoreCase: false
  no-var:
    - error
