FROM node:17

ARG db_host

ARG db_port

WORKDIR /api

EXPOSE 4000

COPY . .

COPY ./package.json ./package.json

RUN npm i

RUN chmod 777 ./scripts/wait-for-it.bash

SHELL ["/bin/bash", "-c"]

CMD [ "npm", "run", "docker:serve" ]
