FROM node:17.2-alpine3.14

ARG db_host

ARG db_port

ENV NODE_NAME=test

WORKDIR /api

EXPOSE 4000

COPY . .

COPY ./package.json ./package.json

RUN npm i

RUN chmod 777 ./scripts/wait-for-it.bash

RUN ./scripts/wait-for-it.bash -t 0 -h ${db_host} -p ${db_port} -- echo "database ready."

CMD ["npm", "run", "dev"]
